# Generated by Django 4.2.30 on 2026-06-09 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variety', models.CharField(blank=True, max_length=255)),
                ('planted_at', models.DateField(blank=True, null=True)),
                ('expected_harvest_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('area_planted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['farm', 'status'], name='crops_crop_farm_id_f0856c_idx')],
            },
        ),
    ]
