# Generated by Django 6.0.5 on 2026-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=150)),
                ('specialty', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Orthopedist', 'Orthopedist'), ('Neurologist', 'Neurologist'), ('General Practitioner', 'General Practitioner'), ('Ophthalmologist', 'Ophthalmologist'), ('Dentist', 'Dentist')], default='General Practitioner', max_length=50)),
                ('clinic_name', models.CharField(help_text='Clinic or hospital name', max_length=150)),
                ('address', models.CharField(help_text='Full physical address', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinates (auto-filled if empty and API key is set)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinates (auto-filled if empty and API key is set)', max_digits=9, null=True)),
                ('phone_number', models.CharField(help_text='Contact number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Rating from 1.0 to 5.0', max_digits=3)),
                ('website', models.URLField(blank=True, help_text='Doctor or clinic website URL')),
            ],
        ),
    ]
