# Generated by Django 6.0.5 on 2026-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('Allergist/Immunologist', 'Allergist/Immunologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Family Physician', 'Family Physician'), ('Gastroenterologist', 'Gastroenterologist'), ('Hematologist', 'Hematologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Internist', 'Internist'), ('Medical Geneticist', 'Medical Geneticist'), ('Nephrologist', 'Nephrologist'), ('Neurologist', 'Neurologist'), ('Obstetrician/Gynecologist', 'Obstetrician/Gynecologist'), ('Oncologist', 'Oncologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Otolaryngologist', 'Otolaryngologist (ENT)'), ('Pathologist', 'Pathologist'), ('Pediatrician', 'Pediatrician'), ('Physiatrist', 'Physiatrist'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Psychiatrist', 'Psychiatrist'), ('Pulmonologist', 'Pulmonologist'), ('Radiologist', 'Radiologist'), ('Rheumatologist', 'Rheumatologist'), ('Surgeon', 'General Surgeon'), ('Urologist', 'Urologist'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
