# Generated by Django 6.0.5 on 2026-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_doctorprofile_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('Allergy and Immunology', 'Allergy and Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Cardiothoracic Surgery', 'Cardiothoracic Surgery'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Emergency Medicine', 'Emergency Medicine'), ('Family Medicine', 'Family Medicine'), ('Gastroenterology', 'Gastroenterology'), ('General Surgery', 'General Surgery'), ('Geriatrics', 'Geriatrics'), ('Hematology', 'Hematology'), ('Infectious Disease', 'Infectious Disease'), ('Internal Medicine', 'Internal Medicine'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Neurosurgery', 'Neurosurgery'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedic Surgery', 'Orthopedic Surgery'), ('Otolaryngology (ENT)', 'Otolaryngology (ENT)'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation'), ('Plastic Surgery', 'Plastic Surgery'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Radiology', 'Radiology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology'), ('Vascular Surgery', 'Vascular Surgery'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
