# Generated by Django 4.2 on 2026-04-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_studinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
