# Generated by Django 4.2 on 2026-04-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_studinfo_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studinfo',
            name='dob',
        ),
    ]
