# Generated by Django 6.0.5 on 2026-06-09 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='harvested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
