# Generated by Django 6.0.5 on 2026-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, help_text='Room preferences or type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seat',
            field=models.CharField(blank=True, help_text='Selected seat for flight (e.g., 12A)', max_length=10, null=True),
        ),
    ]
